# Generated by Django 3.2.9 on 2021-12-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('rating', models.FloatField(default=0)),
                ('country', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('nutrition', models.TextField()),
                ('allergens', models.TextField()),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
    ]
