# Generated by Django 3.2.9 on 2021-12-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211210_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['date']},
        ),
    ]
