# Generated by Django 3.2.9 on 2021-12-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviews_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={},
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='active',
        ),
    ]
