# Generated by Django 3.2.9 on 2021-12-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211212_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['-date']},
        ),
    ]
