# Generated by Django 3.2.9 on 2021-12-12 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_reviews_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='name',
        ),
    ]
