# Generated by Django 3.2.9 on 2021-12-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_user_reviews_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
