# Generated by Django 3.2.9 on 2021-12-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
